# Generated by Django 2.2 on 2019-07-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadictionarycategorymodel',
            name='data_type',
            field=models.IntegerField(choices=[(1, 'data'), (2, 'config')], default=1, null=True, verbose_name='Dictionary Type'),
        ),
    ]
