# Generated by Django 2.2 on 2019-07-12 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturerulemodel',
            name='cookies',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='capture_cookie', to='rule.CaptureRuleCookieModel', verbose_name='Cookies'),
        ),
        migrations.AlterField(
            model_name='capturerulemodel',
            name='user_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(''), related_name='capture_user_agent', to='rule.CaptureRuleUserAgentModel', verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='captureruleurlmodel',
            name='capture_rule',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='capture_rule_urls', to='rule.CaptureRuleModel', verbose_name='rule'),
        ),
    ]
