# Generated by Django 2.2 on 2019-07-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190715_1656'),
        ('rule', '0002_auto_20190712_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturerulemodel',
            name='proxy',
            field=models.OneToOneField(null=True, on_delete=models.SET(''), related_name='proxy', to='system.ProxyIpModel', verbose_name='Proxy'),
        ),
        migrations.AddField(
            model_name='capturerulemodel',
            name='proxy_used',
            field=models.IntegerField(choices=[(1, 'Multi Proxy'), (2, 'Single Proxy'), (3, 'Not use Proxy')], default=3, null=True, verbose_name='Use the proxy'),
        ),
        migrations.AddField(
            model_name='capturerulemodel',
            name='proxys_country',
            field=models.ManyToManyField(null=True, related_name='proxys_country', to='system.RegionModel', verbose_name='Proxys Country'),
        ),
        migrations.AddField(
            model_name='capturerulemodel',
            name='proxys_num',
            field=models.IntegerField(default=0, null=True, verbose_name='Proxys Num'),
        ),
    ]
