# Generated by Django 2.2 on 2019-07-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190715_1656'),
        ('rule', '0003_auto_20190716_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capturerulemodel',
            name='proxys_country',
        ),
        migrations.AddField(
            model_name='capturerulemodel',
            name='proxys_city',
            field=models.ManyToManyField(to='system.RegionModel', verbose_name='Proxys City'),
        ),
        migrations.AlterField(
            model_name='capturerulemodel',
            name='proxy',
            field=models.OneToOneField(blank=True, null=True, on_delete=models.SET(''), related_name='proxy', to='system.ProxyIpModel', verbose_name='Proxy'),
        ),
    ]
