# Generated by Django 2.2.3 on 2019-07-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0006_auto_20190725_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrulemodel',
            name='analysis_at',
            field=models.DateTimeField(null=True, verbose_name='Analysis At'),
        ),
    ]
