# Generated by Django 2.2.3 on 2019-07-29 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0007_analysisrulemodel_analysis_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrulemodel',
            name='sync_at',
            field=models.DateTimeField(null=True, verbose_name='Sync At'),
        ),
    ]
