# Generated by Django 2.2 on 2019-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0007_analysisrulemodel_analysis_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='capturerulemodel',
            name='slice',
            field=models.IntegerField(default=300, null=True, verbose_name='Request Slice'),
        ),
        migrations.AddField(
            model_name='capturerulemodel',
            name='spider_name',
            field=models.CharField(default='CaptureSpider', max_length=200, null=True, verbose_name='Spider Name'),
        ),
        migrations.AddField(
            model_name='captureruleurlmodel',
            name='condition',
            field=models.TextField(default='', help_text='This is a JSON Format field', null=True, verbose_name='Url Params Condition'),
        ),
        migrations.AlterField(
            model_name='capturerulemodel',
            name='delay',
            field=models.IntegerField(default=2, help_text='Request Delay must bigger 1 Second!!', null=True, verbose_name='Request Delay'),
        ),
        migrations.AlterField(
            model_name='captureruleurlmodel',
            name='path',
            field=models.TextField(default='', null=True, verbose_name='Url Path'),
        ),
    ]
