# Generated by Django 2.1.7 on 2019-07-30 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0008_analysisrulemodel_sync_at'),
        ('rule', '0008_auto_20190729_1323'),
    ]

    operations = [
    ]
