# Generated by Django 2.2.3 on 2019-08-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0009_merge_20190730_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrulemodel',
            name='analysis_last_id',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Analysis Last Id'),
        ),
        migrations.AddField(
            model_name='analysisrulemodel',
            name='sync_last_id',
            field=models.BigIntegerField(default=0, null=True, verbose_name='Sync Last Id'),
        ),
    ]
