# Generated by Django 2.1.5 on 2019-06-28 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CronjobConfigModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Key')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('creator', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cronjob Config',
                'verbose_name_plural': 'Cronjob Config',
                'db_table': 'na_cronjob_job_config',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='CronjobJobStoreModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('next_run_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('job_state', models.BinaryField()),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Task List',
                'verbose_name_plural': 'Task List',
                'db_table': 'na_cronjob_job_store',
                'ordering': ('next_run_time',),
            },
        ),
        migrations.CreateModel(
            name='CronjobLogsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Successful'), (2, 'Unsuccessful'), (3, 'Error')], default=1, editable=False, verbose_name='Status')),
                ('content', models.TextField(max_length=10000, null=True, verbose_name='Content')),
                ('process', models.CharField(max_length=100, null=True, verbose_name='Process ID')),
                ('thread', models.IntegerField(null=True, verbose_name='Thread ID')),
                ('time_long', models.FloatField(default=0, verbose_name='Time Long')),
                ('date_begin', models.DateTimeField(null=True, verbose_name='Begin')),
                ('date_end', models.DateTimeField(null=True, verbose_name='End')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Logs for Run',
                'verbose_name_plural': 'Logs for Run',
                'db_table': 'na_cronjob_logs',
            },
        ),
        migrations.CreateModel(
            name='CronjobModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Only once'), (2, 'Repeating')], default=2, verbose_name='Type')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('yr', models.CharField(default='*', max_length=100, verbose_name='Year')),
                ('mo', models.CharField(default='*', max_length=255, verbose_name='Month')),
                ('dy', models.CharField(default='*', max_length=255, verbose_name='Day')),
                ('wk', models.CharField(default='*', max_length=255, verbose_name='Week')),
                ('dy_of_week', models.CharField(default='*', max_length=255, verbose_name='Day of Week')),
                ('hr', models.CharField(default='*', max_length=255, verbose_name='Hour')),
                ('mi', models.CharField(default='*', max_length=255, verbose_name='Minute')),
                ('se', models.CharField(default='*', max_length=255, verbose_name='Second')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(null=True, verbose_name='End Date')),
                ('timezone', models.CharField(choices=[('Australia/Melbourne', 'Australia/Melbourne'), ('Asia/Shanghai', 'Asia/Shanghai')], max_length=100, null=True, verbose_name='Timezone')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, verbose_name='Status')),
                ('command', models.TextField(max_length=5000, null=True, verbose_name='Command')),
                ('command_type', models.IntegerField(choices=[(1, 'Inner Program'), (2, 'System Shell')], null=True, verbose_name='Command Type')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cronjob Set',
                'verbose_name_plural': 'Cronjob Set',
                'db_table': 'na_cronjob',
            },
        ),
        migrations.CreateModel(
            name='CronjobStateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Successfuly'), (2, 'Failed')], default=2, editable=False, verbose_name='Status')),
                ('action', models.IntegerField(choices=[(1, 'Start'), (2, 'Stop')], default=2, editable=False, verbose_name='Action')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('cronjob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cronjob.CronjobModel')),
            ],
            options={
                'verbose_name': 'Logs for Load',
                'verbose_name_plural': 'Logs for Load',
                'db_table': 'na_cronjob_state',
            },
        ),
        migrations.AddField(
            model_name='cronjoblogsmodel',
            name='cronjob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cronjob.CronjobModel'),
        ),
    ]
