# Generated by Django 2.1.3 on 2019-07-09 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjobmodel',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'Capture'), (2, 'Transformation'), (3, 'Analysis'), (4, 'Message'), (5, 'Report'), (6, 'Other')], default=1, verbose_name='Task Type'),
        ),
    ]
