# Generated by Django 2.2.3 on 2019-07-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0002_cronjobmodel_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobmodel',
            name='command_type',
            field=models.IntegerField(choices=[(1, 'Inner Program'), (2, 'System Shell'), (3, 'System Rule')], null=True, verbose_name='Command Type'),
        ),
    ]
