# Generated by Django 2.2 on 2019-07-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0004_auto_20190712_1103'),
        ('cronjob', '0005_auto_20190711_1636'),
    ]

    operations = [
    ]
