# Generated by Django 2.2.3 on 2019-07-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0006_merge_20190712_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjoblogsmodel',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'Capture'), (2, 'Transformation'), (3, 'Analysis'), (4, 'Message'), (5, 'Report'), (9, 'Other')], default=1, verbose_name='Task Type'),
        ),
        migrations.AddField(
            model_name='cronjobstatemodel',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'Capture'), (2, 'Transformation'), (3, 'Analysis'), (4, 'Message'), (5, 'Report'), (9, 'Other')], default=1, verbose_name='Task Type'),
        ),
    ]
