# Generated by Django 2.2.3 on 2019-07-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0008_cronjobjobstoremodel_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronjobjobstoremodel',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'Capture'), (2, 'Transformation'), (3, 'Analysis'), (4, 'Message'), (5, 'Report'), (9, 'Other')], null=True, verbose_name='Task Type'),
        ),
        migrations.AlterField(
            model_name='cronjoblogsmodel',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'Capture'), (2, 'Transformation'), (3, 'Analysis'), (4, 'Message'), (5, 'Report'), (9, 'Other')], null=True, verbose_name='Task Type'),
        ),
        migrations.AlterField(
            model_name='cronjobstatemodel',
            name='task_type',
            field=models.IntegerField(choices=[(1, 'Capture'), (2, 'Transformation'), (3, 'Analysis'), (4, 'Message'), (5, 'Report'), (9, 'Other')], null=True, verbose_name='Task Type'),
        ),
    ]
