# Generated by Django 2.2.3 on 2019-07-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0009_auto_20190715_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronjobjobstoremodel',
            name='cronjob_id',
            field=models.IntegerField(null=True, verbose_name='Cronjob'),
        ),
    ]
