# Generated by Django 2.2 on 2019-07-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_captureskupricemodel_statamazonskupricelogdaydv_statamazonskupricelogmonthdv_statamazonskupricelogwe'),
        ('appfront', '0002_auto_20190710_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productasinmodel',
            name='category',
        ),
        migrations.AddField(
            model_name='productasinmodel',
            name='category',
            field=models.ManyToManyField(to='amazon.ProductCategoryModel', verbose_name='Category'),
        ),
        migrations.DeleteModel(
            name='ProductCategoryModel',
        ),
    ]
