# Generated by Django 2.2.3 on 2019-07-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_auto_20190716_1628'),
        ('appfront', '0003_auto_20190711_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAsinLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('creator_id', models.IntegerField(editable=False, null=True, verbose_name='Creator')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True, verbose_name='Status')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='Sort')),
                ('sku', models.CharField(max_length=100, null=True, verbose_name='Product SKU')),
                ('modify_fields', models.CharField(max_length=200, null=True, verbose_name='Modify Field')),
                ('old_val', models.TextField(null=True, verbose_name='Old Value')),
                ('new_val', models.TextField(null=True, verbose_name='New Value')),
            ],
            options={
                'verbose_name': 'Product Modify Log',
                'verbose_name_plural': 'Product Modify Logs',
                'db_table': 'na_product_mod_log',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('creator_id', models.IntegerField(editable=False, null=True, verbose_name='Creator')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True, verbose_name='Status')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='Sort')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Product Category')),
                ('modify_fields', models.CharField(max_length=200, null=True, verbose_name='Modify Field')),
                ('old_val', models.TextField(null=True, verbose_name='Old Value')),
                ('new_val', models.TextField(null=True, verbose_name='New Value')),
            ],
            options={
                'verbose_name': 'Product Category Modify Log',
                'verbose_name_plural': 'Product Category  Modify Logs',
                'db_table': 'pub_product_category_mod_log',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('creator_id', models.IntegerField(editable=False, null=True, verbose_name='Creator')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True, verbose_name='Status')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='Sort')),
                ('code', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Category Code')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('level', models.IntegerField(default=0, verbose_name='Level')),
                ('amazon_category', models.ManyToManyField(related_name='amazon_category', to='amazon.ProductCategoryModel', verbose_name='Amazon Category')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appfront.ProductCategoryModel')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Category',
                'db_table': 'pub_product_category',
            },
        ),
        migrations.AddField(
            model_name='productasinmodel',
            name='amazon_category',
            field=models.ManyToManyField(to='amazon.ProductCategoryModel', verbose_name='Amazon Category'),
        ),
        migrations.AlterField(
            model_name='productasinmodel',
            name='asin',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Asin'),
        ),
        migrations.AlterField(
            model_name='productasinmodel',
            name='category',
            field=models.ManyToManyField(to='appfront.ProductCategoryModel', verbose_name='Category'),
        ),
    ]
