# Generated by Django 2.2 on 2019-07-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0004_auto_20190716_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlinemodel',
            name='code',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Code'),
        ),
    ]
