# Generated by Django 2.2 on 2019-07-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0008_auto_20190722_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasinmodel',
            name='category',
            field=models.ManyToManyField(through='appfront.ProductCategoryRelationModel', to='appfront.ProductCategoryModel', verbose_name='Category'),
        ),
    ]
