# Generated by Django 2.2 on 2019-07-22 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0009_productasinmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategoryrelationmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfront.ProductCategoryModel'),
        ),
        migrations.AlterField(
            model_name='productcategoryrelationmodel',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appfront.ProductAsinModel'),
        ),
    ]
