# Generated by Django 2.2 on 2019-07-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_auto_20190716_1628'),
        ('appfront', '0010_auto_20190722_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAsinSkuKeywordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.SkuKeywordModel')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_product_relation', to='appfront.ProductAsinModel')),
            ],
            options={
                'db_table': 'pub_product_asin_keyword_relation',
            },
        ),
        migrations.AddField(
            model_name='productasinmodel',
            name='keyword',
            field=models.ManyToManyField(through='appfront.ProductAsinSkuKeywordRelation', to='amazon.SkuKeywordModel', verbose_name='Keyword'),
        ),
    ]
