# Generated by Django 2.2 on 2019-08-07 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0011_auto_20190722_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='productasinmodel',
            name='combine_type',
            field=models.IntegerField(choices=[(1, 'Single SKU'), (2, 'Combo SKU'), (3, 'Variation SKU'), (4, 'FBA SKU'), (5, 'Parent SKU')], default=1, null=True, verbose_name='Product Combine Type'),
        ),
        migrations.AlterField(
            model_name='productasinmodel',
            name='asin',
            field=models.CharField(help_text='Amazon Platform Product Code', max_length=20, null=True, verbose_name='Asin'),
        ),
        migrations.CreateModel(
            name='ProductAsinCombineRelationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_id', to='appfront.ProductAsinModel', verbose_name='Combine Product Id')),
                ('related_product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_product_id', to='appfront.ProductAsinModel', verbose_name='Related Product Id')),
            ],
            options={
                'db_table': 'na_product_asin_combine_relation',
            },
        ),
        migrations.AddField(
            model_name='productasinmodel',
            name='combine_relation',
            field=models.ManyToManyField(related_name='combine_product_relation', through='appfront.ProductAsinCombineRelationModel', to='appfront.ProductAsinModel', verbose_name='Product Combine Relation'),
        ),
    ]
