# Generated by Django 2.2 on 2019-08-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0012_auto_20190807_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productasincombinerelationmodel',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productasincombinerelationmodel',
            old_name='related_product_id',
            new_name='related_product',
        ),
    ]
