# Generated by Django 2.1.5 on 2019-07-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Platform Setting',
                'verbose_name_plural': 'Platform Setting',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='proxyipmodel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='proxyipmodel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='proxyipmodel',
            name='priority',
            field=models.IntegerField(default=0, null=True, verbose_name='Priority'),
        ),
        migrations.AddField(
            model_name='proxyipmodel',
            name='region_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Region Code'),
        ),
        migrations.AddField(
            model_name='proxyipmodel',
            name='test_result',
            field=models.IntegerField(choices=[(0, 'NO TEST'), (1, 'TEST OK'), (2, 'TEST ERROR')], default=0, null=True, verbose_name='TEST RESULT'),
        ),
        migrations.AlterField(
            model_name='proxyipmodel',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
    ]
