# Generated by Django 2.1.5 on 2019-07-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20190702_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionIpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('creator_id', models.IntegerField(editable=False, null=True, verbose_name='Creator')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True, verbose_name='Status')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='Sort')),
                ('country', models.CharField(max_length=100, null=True, verbose_name='Country')),
                ('country_code', models.CharField(max_length=50, null=True, verbose_name='Country Code')),
                ('region', models.CharField(max_length=100, null=True, verbose_name='Region')),
                ('region_code', models.CharField(max_length=100, null=True, verbose_name='Region Code')),
                ('city', models.CharField(max_length=100, null=True, verbose_name='City')),
                ('locale', models.CharField(max_length=50, null=True, verbose_name='Locale')),
                ('timezone', models.CharField(max_length=100, null=True, verbose_name='Timezone')),
                ('ip_from', models.BigIntegerField(default=0, null=True, verbose_name='Ip From')),
                ('ip_to', models.BigIntegerField(default=0, null=True, verbose_name='Ip To')),
            ],
            options={
                'verbose_name': 'Region Ip',
                'verbose_name_plural': 'Region Ip',
                'db_table': 'system_region_ip',
            },
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='ip_section',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='locale',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='timezone',
        ),
        migrations.AlterField(
            model_name='proxyipmodel',
            name='test_result',
            field=models.IntegerField(choices=[(0, 'No Test'), (1, 'Test OK'), (2, 'Test Error')], default=0, null=True, verbose_name='Test Result'),
        ),
    ]
