# Generated by Django 2.2.3 on 2019-07-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_proxyiplogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('creator_id', models.IntegerField(editable=False, null=True, verbose_name='Creator')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True, verbose_name='Status')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='Sort')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('send_status', models.IntegerField(choices=[(1, 'Successful'), (2, 'Unsuccessful'), (3, 'Error')], default=2, editable=False, verbose_name='Send Status')),
                ('sending_type', models.CharField(blank=True, max_length=50, verbose_name='Sending Type')),
                ('content', models.TextField(max_length=10000, null=True, verbose_name='Content')),
                ('condition', models.CharField(blank=True, max_length=255, verbose_name='Condition')),
                ('group_name', models.CharField(blank=True, max_length=50, verbose_name='Group Name')),
                ('token', models.CharField(blank=True, max_length=100, verbose_name='Token')),
                ('message_type', models.CharField(blank=True, max_length=50, verbose_name='Message Type')),
            ],
            options={
                'verbose_name': 'Message Content',
                'verbose_name_plural': 'Message Content',
                'db_table': 'system_message_content',
            },
        ),
        migrations.AlterField(
            model_name='proxyipmodel',
            name='agent_type',
            field=models.IntegerField(choices=[(1, 'Https'), (2, 'Http'), (3, 'Other')], default=1, null=True, verbose_name='Agent Type'),
        ),
    ]
