# Generated by Django 2.2.3 on 2019-07-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20190711_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templaterunlogmodel',
            name='sku_buy_box_state',
        ),
        migrations.RemoveField(
            model_name='templaterunlogmodel',
            name='template',
        ),
        migrations.AddField(
            model_name='templaterunlogmodel',
            name='sku_buy_box_state_id',
            field=models.IntegerField(editable=False, null=True, verbose_name='Buy Box State'),
        ),
        migrations.AddField(
            model_name='templaterunlogmodel',
            name='template_id',
            field=models.IntegerField(editable=False, null=True, verbose_name='template'),
        ),
    ]
