# Generated by Django 2.2.3 on 2019-07-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190715_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverconfigmodel',
            name='api_list',
        ),
        migrations.RemoveField(
            model_name='serverconfigmodel',
            name='api_version',
        ),
        migrations.RemoveField(
            model_name='serverconfigmodel',
            name='token',
        ),
        migrations.AddField(
            model_name='serverconfigmodel',
            name='instance_id',
            field=models.CharField(max_length=60, null=True, verbose_name='Instance Id'),
        ),
        migrations.AddField(
            model_name='serverconfigmodel',
            name='region_id',
            field=models.CharField(max_length=60, null=True, verbose_name='Region Id'),
        ),
    ]
