from task.admins.TaskCaptureListAdmin import *
from task.admins.TaskTransformationListAdmin import *
from task.admins.TaskAnalysisListAdmin import *
from task.admins.TaskMessageListAdmin import *
from task.admins.TaskReportListAdmin import *
from task.admins.TaskOtherListAdmin import *
from task.admins.TaskCaptureLogsAdmin import *
from task.admins.TaskTransformationLogsAdmin import *
from task.admins.TaskAnalysisLogsAdmin import *
from task.admins.TaskMessageLogsAdmin import *
from task.admins.TaskReportLogsAdmin import *
from task.admins.TaskOtherLogsAdmin import *
