# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formBusinessReport.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BusinessReportForm(object):
    def setupUi(self, BusinessReportForm):
        BusinessReportForm.setObjectName("BusinessReportForm")
        BusinessReportForm.resize(948, 666)
        self.verticalLayout = QtWidgets.QVBoxLayout(BusinessReportForm)
        self.verticalLayout.setContentsMargins(2, 6, 2, 2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lhBusinessReportForm = QtWidgets.QHBoxLayout()
        self.lhBusinessReportForm.setSpacing(2)
        self.lhBusinessReportForm.setObjectName("lhBusinessReportForm")
        self.vlDate = QtWidgets.QVBoxLayout()
        self.vlDate.setObjectName("vlDate")
        self.dateToolBar = QtWidgets.QWidget(BusinessReportForm)
        self.dateToolBar.setMinimumSize(QtCore.QSize(150, 26))
        self.dateToolBar.setObjectName("dateToolBar")
        self.hlDateToolBar = QtWidgets.QHBoxLayout(self.dateToolBar)
        self.hlDateToolBar.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.hlDateToolBar.setContentsMargins(1, 1, 1, 1)
        self.hlDateToolBar.setSpacing(2)
        self.hlDateToolBar.setObjectName("hlDateToolBar")
        self.tbRefresh = QtWidgets.QToolButton(self.dateToolBar)
        self.tbRefresh.setMinimumSize(QtCore.QSize(22, 22))
        self.tbRefresh.setMaximumSize(QtCore.QSize(22, 22))
        self.tbRefresh.setStyleSheet("")
        self.tbRefresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button/images/svg/sync-alt-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbRefresh.setIcon(icon)
        self.tbRefresh.setAutoRaise(True)
        self.tbRefresh.setObjectName("tbRefresh")
        self.hlDateToolBar.addWidget(self.tbRefresh)
        self.tbSearchNav = QtWidgets.QToolButton(self.dateToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbSearchNav.sizePolicy().hasHeightForWidth())
        self.tbSearchNav.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button/images/svg/search-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSearchNav.setIcon(icon1)
        self.tbSearchNav.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.tbSearchNav.setAutoRaise(True)
        self.tbSearchNav.setObjectName("tbSearchNav")
        self.hlDateToolBar.addWidget(self.tbSearchNav)
        self.tbInputCsv = QtWidgets.QToolButton(self.dateToolBar)
        self.tbInputCsv.setMinimumSize(QtCore.QSize(22, 22))
        self.tbInputCsv.setMaximumSize(QtCore.QSize(22, 22))
        self.tbInputCsv.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button/images/svg/file-import-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbInputCsv.setIcon(icon2)
        self.tbInputCsv.setAutoRaise(True)
        self.tbInputCsv.setObjectName("tbInputCsv")
        self.hlDateToolBar.addWidget(self.tbInputCsv)
        self.tbPreview = QtWidgets.QToolButton(self.dateToolBar)
        self.tbPreview.setMinimumSize(QtCore.QSize(22, 22))
        self.tbPreview.setMaximumSize(QtCore.QSize(22, 22))
        self.tbPreview.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/button/images/svg/chart-line-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPreview.setIcon(icon3)
        self.tbPreview.setAutoRaise(True)
        self.tbPreview.setObjectName("tbPreview")
        self.hlDateToolBar.addWidget(self.tbPreview)
        self.widget = QtWidgets.QWidget(self.dateToolBar)
        self.widget.setObjectName("widget")
        self.hlDateToolBar.addWidget(self.widget)
        self.vlDate.addWidget(self.dateToolBar)
        self.twSubNav = QtWidgets.QTabWidget(BusinessReportForm)
        self.twSubNav.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.twSubNav.setObjectName("twSubNav")
        self.tabSku = QtWidgets.QWidget()
        self.tabSku.setObjectName("tabSku")
        self.vlTabSku = QtWidgets.QVBoxLayout(self.tabSku)
        self.vlTabSku.setContentsMargins(0, 0, 0, 0)
        self.vlTabSku.setSpacing(0)
        self.vlTabSku.setObjectName("vlTabSku")
        self.twSkuList = QtWidgets.QTableWidget(self.tabSku)
        self.twSkuList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twSkuList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twSkuList.setObjectName("twSkuList")
        self.twSkuList.setColumnCount(3)
        self.twSkuList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twSkuList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twSkuList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twSkuList.setHorizontalHeaderItem(2, item)
        self.twSkuList.horizontalHeader().setHighlightSections(False)
        self.vlTabSku.addWidget(self.twSkuList)
        self.twSubNav.addTab(self.tabSku, "")
        self.tabDate = QtWidgets.QWidget()
        self.tabDate.setObjectName("tabDate")
        self.vlTabDate = QtWidgets.QVBoxLayout(self.tabDate)
        self.vlTabDate.setContentsMargins(0, 0, 0, 0)
        self.vlTabDate.setSpacing(0)
        self.vlTabDate.setObjectName("vlTabDate")
        self.twDateList = QtWidgets.QTableWidget(self.tabDate)
        self.twDateList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twDateList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twDateList.setObjectName("twDateList")
        self.twDateList.setColumnCount(1)
        self.twDateList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twDateList.setHorizontalHeaderItem(0, item)
        self.twDateList.horizontalHeader().setHighlightSections(False)
        self.vlTabDate.addWidget(self.twDateList)
        self.twSubNav.addTab(self.tabDate, "")
        self.vlDate.addWidget(self.twSubNav)
        self.lhBusinessReportForm.addLayout(self.vlDate)
        self.lineVerTabSpace = QtWidgets.QToolButton(BusinessReportForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineVerTabSpace.sizePolicy().hasHeightForWidth())
        self.lineVerTabSpace.setSizePolicy(sizePolicy)
        self.lineVerTabSpace.setMinimumSize(QtCore.QSize(2, 0))
        self.lineVerTabSpace.setMaximumSize(QtCore.QSize(2, 16777215))
        self.lineVerTabSpace.setCursor(QtGui.QCursor(QtCore.Qt.SplitHCursor))
        self.lineVerTabSpace.setText("")
        self.lineVerTabSpace.setAutoRaise(True)
        self.lineVerTabSpace.setObjectName("lineVerTabSpace")
        self.lhBusinessReportForm.addWidget(self.lineVerTabSpace)
        self.vlReport = QtWidgets.QWidget(BusinessReportForm)
        self.vlReport.setEnabled(True)
        self.vlReport.setMinimumSize(QtCore.QSize(100, 0))
        self.vlReport.setObjectName("vlReport")
        self.vlReportC = QtWidgets.QVBoxLayout(self.vlReport)
        self.vlReportC.setContentsMargins(0, 0, 0, 0)
        self.vlReportC.setObjectName("vlReportC")
        self.reportToolBar = QtWidgets.QWidget(self.vlReport)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reportToolBar.sizePolicy().hasHeightForWidth())
        self.reportToolBar.setSizePolicy(sizePolicy)
        self.reportToolBar.setMinimumSize(QtCore.QSize(0, 26))
        self.reportToolBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.reportToolBar.setObjectName("reportToolBar")
        self.hlReportToolBar = QtWidgets.QHBoxLayout(self.reportToolBar)
        self.hlReportToolBar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hlReportToolBar.setContentsMargins(1, 1, 1, 1)
        self.hlReportToolBar.setSpacing(2)
        self.hlReportToolBar.setObjectName("hlReportToolBar")
        self.tbSelection = QtWidgets.QToolButton(self.reportToolBar)
        self.tbSelection.setMinimumSize(QtCore.QSize(22, 22))
        self.tbSelection.setMaximumSize(QtCore.QSize(22, 22))
        self.tbSelection.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/button/images/svg/check-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSelection.setIcon(icon4)
        self.tbSelection.setAutoRaise(True)
        self.tbSelection.setObjectName("tbSelection")
        self.hlReportToolBar.addWidget(self.tbSelection)
        self.tbUnselection = QtWidgets.QToolButton(self.reportToolBar)
        self.tbUnselection.setMinimumSize(QtCore.QSize(22, 22))
        self.tbUnselection.setMaximumSize(QtCore.QSize(22, 22))
        self.tbUnselection.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/button/images/svg/times-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbUnselection.setIcon(icon5)
        self.tbUnselection.setAutoRaise(True)
        self.tbUnselection.setObjectName("tbUnselection")
        self.hlReportToolBar.addWidget(self.tbUnselection)
        self.tbInvertSelection = QtWidgets.QToolButton(self.reportToolBar)
        self.tbInvertSelection.setMinimumSize(QtCore.QSize(22, 22))
        self.tbInvertSelection.setMaximumSize(QtCore.QSize(22, 22))
        self.tbInvertSelection.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/button/images/svg/retweet-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbInvertSelection.setIcon(icon6)
        self.tbInvertSelection.setAutoRaise(True)
        self.tbInvertSelection.setObjectName("tbInvertSelection")
        self.hlReportToolBar.addWidget(self.tbInvertSelection)
        self.line_2 = QtWidgets.QFrame(self.reportToolBar)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hlReportToolBar.addWidget(self.line_2)
        self.tbSearchDetails = QtWidgets.QToolButton(self.reportToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbSearchDetails.sizePolicy().hasHeightForWidth())
        self.tbSearchDetails.setSizePolicy(sizePolicy)
        self.tbSearchDetails.setIcon(icon1)
        self.tbSearchDetails.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.tbSearchDetails.setAutoRaise(True)
        self.tbSearchDetails.setObjectName("tbSearchDetails")
        self.hlReportToolBar.addWidget(self.tbSearchDetails)
        self.tbDelete = QtWidgets.QToolButton(self.reportToolBar)
        self.tbDelete.setMinimumSize(QtCore.QSize(22, 22))
        self.tbDelete.setMaximumSize(QtCore.QSize(22, 22))
        self.tbDelete.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/button/images/svg/times-circle-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbDelete.setIcon(icon7)
        self.tbDelete.setAutoRaise(True)
        self.tbDelete.setObjectName("tbDelete")
        self.hlReportToolBar.addWidget(self.tbDelete)
        self.line = QtWidgets.QFrame(self.reportToolBar)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hlReportToolBar.addWidget(self.line)
        self.tbPagerHome = QtWidgets.QToolButton(self.reportToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbPagerHome.sizePolicy().hasHeightForWidth())
        self.tbPagerHome.setSizePolicy(sizePolicy)
        self.tbPagerHome.setMinimumSize(QtCore.QSize(22, 22))
        self.tbPagerHome.setMaximumSize(QtCore.QSize(22, 22))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/button/images/svg/step-backward-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPagerHome.setIcon(icon8)
        self.tbPagerHome.setIconSize(QtCore.QSize(15, 15))
        self.tbPagerHome.setAutoRaise(True)
        self.tbPagerHome.setObjectName("tbPagerHome")
        self.hlReportToolBar.addWidget(self.tbPagerHome)
        self.tbPagerUp = QtWidgets.QToolButton(self.reportToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbPagerUp.sizePolicy().hasHeightForWidth())
        self.tbPagerUp.setSizePolicy(sizePolicy)
        self.tbPagerUp.setMinimumSize(QtCore.QSize(22, 22))
        self.tbPagerUp.setMaximumSize(QtCore.QSize(22, 22))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/button/images/svg/caret-left-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPagerUp.setIcon(icon9)
        self.tbPagerUp.setAutoRepeat(False)
        self.tbPagerUp.setAutoExclusive(False)
        self.tbPagerUp.setAutoRaise(True)
        self.tbPagerUp.setArrowType(QtCore.Qt.NoArrow)
        self.tbPagerUp.setObjectName("tbPagerUp")
        self.hlReportToolBar.addWidget(self.tbPagerUp)
        self.tbPagerDown = QtWidgets.QToolButton(self.reportToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbPagerDown.sizePolicy().hasHeightForWidth())
        self.tbPagerDown.setSizePolicy(sizePolicy)
        self.tbPagerDown.setMinimumSize(QtCore.QSize(22, 22))
        self.tbPagerDown.setMaximumSize(QtCore.QSize(22, 22))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/button/images/svg/caret-right-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPagerDown.setIcon(icon10)
        self.tbPagerDown.setAutoRaise(True)
        self.tbPagerDown.setArrowType(QtCore.Qt.NoArrow)
        self.tbPagerDown.setObjectName("tbPagerDown")
        self.hlReportToolBar.addWidget(self.tbPagerDown)
        self.tbPagerEnd = QtWidgets.QToolButton(self.reportToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbPagerEnd.sizePolicy().hasHeightForWidth())
        self.tbPagerEnd.setSizePolicy(sizePolicy)
        self.tbPagerEnd.setMinimumSize(QtCore.QSize(22, 22))
        self.tbPagerEnd.setMaximumSize(QtCore.QSize(22, 22))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/button/images/svg/step-forward-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbPagerEnd.setIcon(icon11)
        self.tbPagerEnd.setIconSize(QtCore.QSize(15, 15))
        self.tbPagerEnd.setShortcut("")
        self.tbPagerEnd.setAutoRaise(True)
        self.tbPagerEnd.setObjectName("tbPagerEnd")
        self.hlReportToolBar.addWidget(self.tbPagerEnd)
        self.lePagerCur = QtWidgets.QLineEdit(self.reportToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lePagerCur.sizePolicy().hasHeightForWidth())
        self.lePagerCur.setSizePolicy(sizePolicy)
        self.lePagerCur.setMinimumSize(QtCore.QSize(40, 0))
        self.lePagerCur.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lePagerCur.setObjectName("lePagerCur")
        self.hlReportToolBar.addWidget(self.lePagerCur)
        self.lbPagerInfo = QtWidgets.QLabel(self.reportToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbPagerInfo.sizePolicy().hasHeightForWidth())
        self.lbPagerInfo.setSizePolicy(sizePolicy)
        self.lbPagerInfo.setObjectName("lbPagerInfo")
        self.hlReportToolBar.addWidget(self.lbPagerInfo)
        self.widget_2 = QtWidgets.QWidget(self.reportToolBar)
        self.widget_2.setObjectName("widget_2")
        self.hlReportToolBar.addWidget(self.widget_2)
        self.vlReportC.addWidget(self.reportToolBar)
        self.twReportList = QtWidgets.QTableWidget(self.vlReport)
        self.twReportList.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twReportList.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.twReportList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twReportList.setObjectName("twReportList")
        self.twReportList.setColumnCount(16)
        self.twReportList.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.twReportList.setHorizontalHeaderItem(15, item)
        self.twReportList.horizontalHeader().setHighlightSections(False)
        self.vlReportC.addWidget(self.twReportList)
        self.lhBusinessReportForm.addWidget(self.vlReport)
        self.lhBusinessReportForm.setStretch(2, 1)
        self.verticalLayout.addLayout(self.lhBusinessReportForm)

        self.retranslateUi(BusinessReportForm)
        self.twSubNav.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(BusinessReportForm)

    def retranslateUi(self, BusinessReportForm):
        _translate = QtCore.QCoreApplication.translate
        BusinessReportForm.setWindowTitle(_translate("BusinessReportForm", "Business Report"))
        BusinessReportForm.setToolTip(_translate("BusinessReportForm", "Input csv file"))
        self.tbRefresh.setToolTip(_translate("BusinessReportForm", "refresh data for all"))
        self.tbSearchNav.setText(_translate("BusinessReportForm", "Go"))
        self.tbSearchNav.setShortcut(_translate("BusinessReportForm", "Ctrl+S"))
        self.twSkuList.setSortingEnabled(True)
        item = self.twSkuList.horizontalHeaderItem(0)
        item.setText(_translate("BusinessReportForm", "SKU"))
        item = self.twSkuList.horizontalHeaderItem(1)
        item.setText(_translate("BusinessReportForm", "ASIN"))
        item = self.twSkuList.horizontalHeaderItem(2)
        item.setText(_translate("BusinessReportForm", "Combine Type"))
        self.twSubNav.setTabText(self.twSubNav.indexOf(self.tabSku), _translate("BusinessReportForm", "Sku List"))
        self.twDateList.setSortingEnabled(True)
        item = self.twDateList.horizontalHeaderItem(0)
        item.setText(_translate("BusinessReportForm", "Date"))
        self.twSubNav.setTabText(self.twSubNav.indexOf(self.tabDate), _translate("BusinessReportForm", "Date List"))
        self.tbSelection.setToolTip(_translate("BusinessReportForm", "selection record(s)"))
        self.tbUnselection.setToolTip(_translate("BusinessReportForm", "unselection record(s)"))
        self.tbInvertSelection.setToolTip(_translate("BusinessReportForm", "Invert selection record(s)"))
        self.tbSearchDetails.setText(_translate("BusinessReportForm", "Go"))
        self.tbSearchDetails.setShortcut(_translate("BusinessReportForm", "Ctrl+S"))
        self.tbDelete.setToolTip(_translate("BusinessReportForm", "delete record(s)"))
        self.tbPagerHome.setText(_translate("BusinessReportForm", "Page Home"))
        self.tbPagerHome.setShortcut(_translate("BusinessReportForm", "Home"))
        self.tbPagerUp.setText(_translate("BusinessReportForm", "Page Up"))
        self.tbPagerUp.setShortcut(_translate("BusinessReportForm", "PgUp"))
        self.tbPagerDown.setText(_translate("BusinessReportForm", "Page Down"))
        self.tbPagerDown.setShortcut(_translate("BusinessReportForm", "PgDown"))
        self.tbPagerEnd.setText(_translate("BusinessReportForm", "Page End"))
        self.lbPagerInfo.setText(_translate("BusinessReportForm", "P:{0} | R:{1}"))
        self.twReportList.setSortingEnabled(True)
        item = self.twReportList.horizontalHeaderItem(0)
        item.setText(_translate("BusinessReportForm", "#"))
        item = self.twReportList.horizontalHeaderItem(1)
        item.setText(_translate("BusinessReportForm", "SKU"))
        item = self.twReportList.horizontalHeaderItem(2)
        item.setText(_translate("BusinessReportForm", "(Parent) ASIN"))
        item = self.twReportList.horizontalHeaderItem(3)
        item.setText(_translate("BusinessReportForm", "(Child) ASIN"))
        item = self.twReportList.horizontalHeaderItem(4)
        item.setText(_translate("BusinessReportForm", "Title"))
        item = self.twReportList.horizontalHeaderItem(5)
        item.setText(_translate("BusinessReportForm", "Sessions"))
        item = self.twReportList.horizontalHeaderItem(6)
        item.setText(_translate("BusinessReportForm", "Session Per."))
        item = self.twReportList.horizontalHeaderItem(7)
        item.setText(_translate("BusinessReportForm", "Page Views"))
        item = self.twReportList.horizontalHeaderItem(8)
        item.setText(_translate("BusinessReportForm", "Page Views Per."))
        item = self.twReportList.horizontalHeaderItem(9)
        item.setText(_translate("BusinessReportForm", "Buy Box Per."))
        item = self.twReportList.horizontalHeaderItem(10)
        item.setText(_translate("BusinessReportForm", "Units Ordered"))
        item = self.twReportList.horizontalHeaderItem(11)
        item.setText(_translate("BusinessReportForm", "Unit Session Per."))
        item = self.twReportList.horizontalHeaderItem(12)
        item.setText(_translate("BusinessReportForm", "Ordered Product Sales"))
        item = self.twReportList.horizontalHeaderItem(13)
        item.setText(_translate("BusinessReportForm", "Total Order Items"))
        item = self.twReportList.horizontalHeaderItem(14)
        item.setText(_translate("BusinessReportForm", "Report Date"))
        item = self.twReportList.horizontalHeaderItem(15)
        item.setText(_translate("BusinessReportForm", "Created At"))


import icons_rc
