# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formSkuKeyword.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AmazonKeywordForm(object):
    def setupUi(self, AmazonKeywordForm):
        AmazonKeywordForm.setObjectName("AmazonKeywordForm")
        AmazonKeywordForm.resize(906, 655)
        self.vlAmazonKeywordForm = QtWidgets.QVBoxLayout(AmazonKeywordForm)
        self.vlAmazonKeywordForm.setContentsMargins(2, 6, 2, 2)
        self.vlAmazonKeywordForm.setSpacing(3)
        self.vlAmazonKeywordForm.setObjectName("vlAmazonKeywordForm")
        self.keywordToolBar = QtWidgets.QWidget(AmazonKeywordForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keywordToolBar.sizePolicy().hasHeightForWidth())
        self.keywordToolBar.setSizePolicy(sizePolicy)
        self.keywordToolBar.setMinimumSize(QtCore.QSize(0, 26))
        self.keywordToolBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.keywordToolBar.setObjectName("keywordToolBar")
        self.hlReportToolBar = QtWidgets.QHBoxLayout(self.keywordToolBar)
        self.hlReportToolBar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hlReportToolBar.setContentsMargins(1, 1, 1, 1)
        self.hlReportToolBar.setSpacing(2)
        self.hlReportToolBar.setObjectName("hlReportToolBar")
        self.tbRefresh = QtWidgets.QToolButton(self.keywordToolBar)
        self.tbRefresh.setMinimumSize(QtCore.QSize(22, 22))
        self.tbRefresh.setMaximumSize(QtCore.QSize(22, 22))
        self.tbRefresh.setStyleSheet("")
        self.tbRefresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button/images/svg/sync-alt-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbRefresh.setIcon(icon)
        self.tbRefresh.setAutoRaise(True)
        self.tbRefresh.setObjectName("tbRefresh")
        self.hlReportToolBar.addWidget(self.tbRefresh)
        self.tbSave = QtWidgets.QToolButton(self.keywordToolBar)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button/images/svg/save-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSave.setIcon(icon1)
        self.tbSave.setObjectName("tbSave")
        self.hlReportToolBar.addWidget(self.tbSave)
        self.tbSelection = QtWidgets.QToolButton(self.keywordToolBar)
        self.tbSelection.setMinimumSize(QtCore.QSize(22, 22))
        self.tbSelection.setMaximumSize(QtCore.QSize(22, 22))
        self.tbSelection.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button/images/svg/check-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSelection.setIcon(icon2)
        self.tbSelection.setAutoRaise(True)
        self.tbSelection.setObjectName("tbSelection")
        self.hlReportToolBar.addWidget(self.tbSelection)
        self.tbUnselection = QtWidgets.QToolButton(self.keywordToolBar)
        self.tbUnselection.setMinimumSize(QtCore.QSize(22, 22))
        self.tbUnselection.setMaximumSize(QtCore.QSize(22, 22))
        self.tbUnselection.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/button/images/svg/times-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbUnselection.setIcon(icon3)
        self.tbUnselection.setAutoRaise(True)
        self.tbUnselection.setObjectName("tbUnselection")
        self.hlReportToolBar.addWidget(self.tbUnselection)
        self.tbInvertSelection = QtWidgets.QToolButton(self.keywordToolBar)
        self.tbInvertSelection.setMinimumSize(QtCore.QSize(22, 22))
        self.tbInvertSelection.setMaximumSize(QtCore.QSize(22, 22))
        self.tbInvertSelection.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/button/images/svg/retweet-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbInvertSelection.setIcon(icon4)
        self.tbInvertSelection.setAutoRaise(True)
        self.tbInvertSelection.setObjectName("tbInvertSelection")
        self.hlReportToolBar.addWidget(self.tbInvertSelection)
        self.line_2 = QtWidgets.QFrame(self.keywordToolBar)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hlReportToolBar.addWidget(self.line_2)
        self.tbSearch = QtWidgets.QToolButton(self.keywordToolBar)
        self.tbSearch.setMinimumSize(QtCore.QSize(22, 22))
        self.tbSearch.setMaximumSize(QtCore.QSize(50, 50))
        self.tbSearch.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/button/images/svg/search-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSearch.setIcon(icon5)
        self.tbSearch.setAutoExclusive(False)
        self.tbSearch.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.tbSearch.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbSearch.setAutoRaise(True)
        self.tbSearch.setArrowType(QtCore.Qt.NoArrow)
        self.tbSearch.setObjectName("tbSearch")
        self.hlReportToolBar.addWidget(self.tbSearch)
        self.tbInputCsv = QtWidgets.QToolButton(self.keywordToolBar)
        self.tbInputCsv.setMinimumSize(QtCore.QSize(22, 22))
        self.tbInputCsv.setMaximumSize(QtCore.QSize(22, 22))
        self.tbInputCsv.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/button/images/svg/file-import-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbInputCsv.setIcon(icon6)
        self.tbInputCsv.setAutoRaise(True)
        self.tbInputCsv.setObjectName("tbInputCsv")
        self.hlReportToolBar.addWidget(self.tbInputCsv)
        self.tbAssociate = QtWidgets.QToolButton(self.keywordToolBar)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/button/images/svg/exchange-alt-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbAssociate.setIcon(icon7)
        self.tbAssociate.setObjectName("tbAssociate")
        self.hlReportToolBar.addWidget(self.tbAssociate)
        self.tbDelete = QtWidgets.QToolButton(self.keywordToolBar)
        self.tbDelete.setMinimumSize(QtCore.QSize(22, 22))
        self.tbDelete.setMaximumSize(QtCore.QSize(22, 22))
        self.tbDelete.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/button/images/svg/times-circle-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbDelete.setIcon(icon8)
        self.tbDelete.setAutoRaise(True)
        self.tbDelete.setObjectName("tbDelete")
        self.hlReportToolBar.addWidget(self.tbDelete)
        self.line = QtWidgets.QFrame(self.keywordToolBar)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hlReportToolBar.addWidget(self.line)
        self.lbPagerInfo = QtWidgets.QLabel(self.keywordToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbPagerInfo.sizePolicy().hasHeightForWidth())
        self.lbPagerInfo.setSizePolicy(sizePolicy)
        self.lbPagerInfo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbPagerInfo.setObjectName("lbPagerInfo")
        self.hlReportToolBar.addWidget(self.lbPagerInfo)
        self.widget_2 = QtWidgets.QWidget(self.keywordToolBar)
        self.widget_2.setObjectName("widget_2")
        self.hlReportToolBar.addWidget(self.widget_2)
        self.vlAmazonKeywordForm.addWidget(self.keywordToolBar)
        self.twAmazonKeyword = QtWidgets.QTableWidget(AmazonKeywordForm)
        self.twAmazonKeyword.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.twAmazonKeyword.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.twAmazonKeyword.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twAmazonKeyword.setObjectName("twAmazonKeyword")
        self.twAmazonKeyword.setColumnCount(6)
        self.twAmazonKeyword.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twAmazonKeyword.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAmazonKeyword.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAmazonKeyword.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAmazonKeyword.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAmazonKeyword.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.twAmazonKeyword.setHorizontalHeaderItem(5, item)
        self.twAmazonKeyword.horizontalHeader().setHighlightSections(False)
        self.vlAmazonKeywordForm.addWidget(self.twAmazonKeyword)
        self.vlAmazonKeywordForm.setStretch(1, 1)

        self.retranslateUi(AmazonKeywordForm)
        QtCore.QMetaObject.connectSlotsByName(AmazonKeywordForm)

    def retranslateUi(self, AmazonKeywordForm):
        _translate = QtCore.QCoreApplication.translate
        AmazonKeywordForm.setWindowTitle(_translate("AmazonKeywordForm", "Amazon Keyword List"))
        self.tbSave.setText(_translate("AmazonKeywordForm", "..."))
        self.tbAssociate.setText(_translate("AmazonKeywordForm", "..."))
        self.lbPagerInfo.setText(_translate("AmazonKeywordForm", "R:{1}"))
        self.twAmazonKeyword.setSortingEnabled(True)
        item = self.twAmazonKeyword.horizontalHeaderItem(0)
        item.setText(_translate("AmazonKeywordForm", "#"))
        item = self.twAmazonKeyword.horizontalHeaderItem(1)
        item.setText(_translate("AmazonKeywordForm", "Title"))
        item = self.twAmazonKeyword.horizontalHeaderItem(2)
        item.setText(_translate("AmazonKeywordForm", "Platform"))
        item = self.twAmazonKeyword.horizontalHeaderItem(3)
        item.setText(_translate("AmazonKeywordForm", "Updated At"))
        item = self.twAmazonKeyword.horizontalHeaderItem(4)
        item.setText(_translate("AmazonKeywordForm", "Created At"))
        item = self.twAmazonKeyword.horizontalHeaderItem(5)
        item.setText(_translate("AmazonKeywordForm", "Edited"))


import icons_rc
