# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormProductLine.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProductLineForm(object):
    def setupUi(self, ProductLineForm):
        ProductLineForm.setObjectName("ProductLineForm")
        ProductLineForm.resize(906, 655)
        self.vlProductLineForm = QtWidgets.QVBoxLayout(ProductLineForm)
        self.vlProductLineForm.setContentsMargins(2, 6, 2, 2)
        self.vlProductLineForm.setSpacing(3)
        self.vlProductLineForm.setObjectName("vlProductLineForm")
        self.productLineToolBar = QtWidgets.QWidget(ProductLineForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productLineToolBar.sizePolicy().hasHeightForWidth())
        self.productLineToolBar.setSizePolicy(sizePolicy)
        self.productLineToolBar.setMinimumSize(QtCore.QSize(0, 26))
        self.productLineToolBar.setInputMethodHints(QtCore.Qt.ImhNone)
        self.productLineToolBar.setObjectName("productLineToolBar")
        self.hlReportToolBar = QtWidgets.QHBoxLayout(self.productLineToolBar)
        self.hlReportToolBar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.hlReportToolBar.setContentsMargins(1, 1, 1, 1)
        self.hlReportToolBar.setSpacing(2)
        self.hlReportToolBar.setObjectName("hlReportToolBar")
        self.tbRefresh = QtWidgets.QToolButton(self.productLineToolBar)
        self.tbRefresh.setMinimumSize(QtCore.QSize(22, 22))
        self.tbRefresh.setMaximumSize(QtCore.QSize(22, 22))
        self.tbRefresh.setStyleSheet("")
        self.tbRefresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button/images/svg/sync-alt-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbRefresh.setIcon(icon)
        self.tbRefresh.setAutoRaise(True)
        self.tbRefresh.setObjectName("tbRefresh")
        self.hlReportToolBar.addWidget(self.tbRefresh)
        self.tbSelection = QtWidgets.QToolButton(self.productLineToolBar)
        self.tbSelection.setMinimumSize(QtCore.QSize(22, 22))
        self.tbSelection.setMaximumSize(QtCore.QSize(22, 22))
        self.tbSelection.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button/images/svg/check-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSelection.setIcon(icon1)
        self.tbSelection.setAutoRaise(True)
        self.tbSelection.setObjectName("tbSelection")
        self.hlReportToolBar.addWidget(self.tbSelection)
        self.tbUnselection = QtWidgets.QToolButton(self.productLineToolBar)
        self.tbUnselection.setMinimumSize(QtCore.QSize(22, 22))
        self.tbUnselection.setMaximumSize(QtCore.QSize(22, 22))
        self.tbUnselection.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button/images/svg/times-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbUnselection.setIcon(icon2)
        self.tbUnselection.setAutoRaise(True)
        self.tbUnselection.setObjectName("tbUnselection")
        self.hlReportToolBar.addWidget(self.tbUnselection)
        self.tbInvertSelection = QtWidgets.QToolButton(self.productLineToolBar)
        self.tbInvertSelection.setMinimumSize(QtCore.QSize(22, 22))
        self.tbInvertSelection.setMaximumSize(QtCore.QSize(22, 22))
        self.tbInvertSelection.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/button/images/svg/retweet-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbInvertSelection.setIcon(icon3)
        self.tbInvertSelection.setAutoRaise(True)
        self.tbInvertSelection.setObjectName("tbInvertSelection")
        self.hlReportToolBar.addWidget(self.tbInvertSelection)
        self.line_2 = QtWidgets.QFrame(self.productLineToolBar)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.hlReportToolBar.addWidget(self.line_2)
        self.tbSearch = QtWidgets.QToolButton(self.productLineToolBar)
        self.tbSearch.setMinimumSize(QtCore.QSize(22, 22))
        self.tbSearch.setMaximumSize(QtCore.QSize(50, 50))
        self.tbSearch.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/button/images/svg/search-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSearch.setIcon(icon4)
        self.tbSearch.setAutoExclusive(False)
        self.tbSearch.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.tbSearch.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.tbSearch.setAutoRaise(True)
        self.tbSearch.setArrowType(QtCore.Qt.NoArrow)
        self.tbSearch.setObjectName("tbSearch")
        self.hlReportToolBar.addWidget(self.tbSearch)
        self.line = QtWidgets.QFrame(self.productLineToolBar)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hlReportToolBar.addWidget(self.line)
        self.lbPagerInfo = QtWidgets.QLabel(self.productLineToolBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbPagerInfo.sizePolicy().hasHeightForWidth())
        self.lbPagerInfo.setSizePolicy(sizePolicy)
        self.lbPagerInfo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbPagerInfo.setObjectName("lbPagerInfo")
        self.hlReportToolBar.addWidget(self.lbPagerInfo)
        self.widget_2 = QtWidgets.QWidget(self.productLineToolBar)
        self.widget_2.setObjectName("widget_2")
        self.hlReportToolBar.addWidget(self.widget_2)
        self.vlProductLineForm.addWidget(self.productLineToolBar)
        self.twProductLine = QtWidgets.QTableWidget(ProductLineForm)
        self.twProductLine.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twProductLine.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.twProductLine.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twProductLine.setObjectName("twProductLine")
        self.twProductLine.setColumnCount(5)
        self.twProductLine.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twProductLine.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twProductLine.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twProductLine.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twProductLine.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twProductLine.setHorizontalHeaderItem(4, item)
        self.twProductLine.horizontalHeader().setHighlightSections(False)
        self.vlProductLineForm.addWidget(self.twProductLine)
        self.vlProductLineForm.setStretch(1, 1)

        self.retranslateUi(ProductLineForm)
        QtCore.QMetaObject.connectSlotsByName(ProductLineForm)

    def retranslateUi(self, ProductLineForm):
        _translate = QtCore.QCoreApplication.translate
        ProductLineForm.setWindowTitle(_translate("ProductLineForm", "Product Line"))
        self.lbPagerInfo.setText(_translate("ProductLineForm", "R:{1}"))
        self.twProductLine.setSortingEnabled(True)
        item = self.twProductLine.horizontalHeaderItem(0)
        item.setText(_translate("ProductLineForm", "#"))
        item = self.twProductLine.horizontalHeaderItem(1)
        item.setText(_translate("ProductLineForm", "Code"))
        item = self.twProductLine.horizontalHeaderItem(2)
        item.setText(_translate("ProductLineForm", "Title"))
        item = self.twProductLine.horizontalHeaderItem(3)
        item.setText(_translate("ProductLineForm", "Updated At"))
        item = self.twProductLine.horizontalHeaderItem(4)
        item.setText(_translate("ProductLineForm", "Created At"))


import icons_rc
