# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1019, 617)
        mainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/winlogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        mainWindow.setAnimated(True)
        mainWindow.setDocumentMode(True)
        mainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        self.widget = QtWidgets.QWidget(mainWindow)
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setContentsMargins(1, 0, 0, 0)
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mainTabs = QtWidgets.QTabWidget(self.widget)
        self.mainTabs.setAcceptDrops(False)
        self.mainTabs.setInputMethodHints(QtCore.Qt.ImhNone)
        self.mainTabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.mainTabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mainTabs.setDocumentMode(True)
        self.mainTabs.setTabsClosable(True)
        self.mainTabs.setMovable(True)
        self.mainTabs.setTabBarAutoHide(False)
        self.mainTabs.setObjectName("mainTabs")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.mainTabs.addTab(self.tab, "")
        self.verticalLayout_4.addWidget(self.mainTabs)
        mainWindow.setCentralWidget(self.widget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1019, 23))
        self.menubar.setObjectName("menubar")
        self.menuSystem = QtWidgets.QMenu(self.menubar)
        self.menuSystem.setStatusTip("")
        self.menuSystem.setStyleSheet("")
        self.menuSystem.setInputMethodHints(QtCore.Qt.ImhNone)
        self.menuSystem.setTearOffEnabled(False)
        self.menuSystem.setSeparatorsCollapsible(True)
        self.menuSystem.setToolTipsVisible(False)
        self.menuSystem.setObjectName("menuSystem")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuKeywords = QtWidgets.QMenu(self.menuTools)
        self.menuKeywords.setObjectName("menuKeywords")
        self.menuCharts = QtWidgets.QMenu(self.menubar)
        self.menuCharts.setObjectName("menuCharts")
        mainWindow.setMenuBar(self.menubar)
        self.actionSetting = QtWidgets.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button/images/svg/cogs-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon1)
        self.actionSetting.setObjectName("actionSetting")
        self.actionExit = QtWidgets.QAction(mainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button/images/svg/sign-out-alt-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(mainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/button/images/svg/lightbulb-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName("actionAbout")
        self.actionBusinessReport = QtWidgets.QAction(mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/button/images/svg/file-csv-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBusinessReport.setIcon(icon4)
        self.actionBusinessReport.setObjectName("actionBusinessReport")
        self.actionProductList = QtWidgets.QAction(mainWindow)
        self.actionProductList.setIcon(icon4)
        self.actionProductList.setObjectName("actionProductList")
        self.actionCategories = QtWidgets.QAction(mainWindow)
        self.actionCategories.setIcon(icon4)
        self.actionCategories.setObjectName("actionCategories")
        self.actionDashboard = QtWidgets.QAction(mainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/button/images/svg/tachometer-alt-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDashboard.setIcon(icon5)
        self.actionDashboard.setObjectName("actionDashboard")
        self.actionChartsBusinessReport = QtWidgets.QAction(mainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/button/images/svg/chart-line-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionChartsBusinessReport.setIcon(icon6)
        self.actionChartsBusinessReport.setObjectName("actionChartsBusinessReport")
        self.actionProduct_Line = QtWidgets.QAction(mainWindow)
        self.actionProduct_Line.setIcon(icon4)
        self.actionProduct_Line.setObjectName("actionProduct_Line")
        self.actionCategory_List = QtWidgets.QAction(mainWindow)
        self.actionCategory_List.setEnabled(False)
        self.actionCategory_List.setIcon(icon4)
        self.actionCategory_List.setObjectName("actionCategory_List")
        self.actionKeywords_List = QtWidgets.QAction(mainWindow)
        self.actionKeywords_List.setIcon(icon4)
        self.actionKeywords_List.setObjectName("actionKeywords_List")
        self.actionProduct_Category_Relation = QtWidgets.QAction(mainWindow)
        self.actionProduct_Category_Relation.setIcon(icon4)
        self.actionProduct_Category_Relation.setObjectName("actionProduct_Category_Relation")
        self.actionProduct_And_Category_Relationship = QtWidgets.QAction(mainWindow)
        self.actionProduct_And_Category_Relationship.setIcon(icon4)
        self.actionProduct_And_Category_Relationship.setObjectName("actionProduct_And_Category_Relationship")
        self.actionAmazon_Keyword_Relation = QtWidgets.QAction(mainWindow)
        self.actionAmazon_Keyword_Relation.setIcon(icon4)
        self.actionAmazon_Keyword_Relation.setIconVisibleInMenu(True)
        self.actionAmazon_Keyword_Relation.setObjectName("actionAmazon_Keyword_Relation")
        self.actionAmazon_Category_Relation = QtWidgets.QAction(mainWindow)
        self.actionAmazon_Category_Relation.setIcon(icon4)
        self.actionAmazon_Category_Relation.setVisible(True)
        self.actionAmazon_Category_Relation.setObjectName("actionAmazon_Category_Relation")
        self.actionHelp = QtWidgets.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/button/images/svg/exclamation-circle-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon7)
        self.actionHelp.setObjectName("actionHelp")
        self.menuSystem.addAction(self.actionDashboard)
        self.menuSystem.addAction(self.actionSetting)
        self.menuSystem.addSeparator()
        self.menuSystem.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionHelp)
        self.menuKeywords.addAction(self.actionKeywords_List)
        self.menuKeywords.addAction(self.actionAmazon_Category_Relation)
        self.menuTools.addAction(self.actionBusinessReport)
        self.menuTools.addAction(self.actionProductList)
        self.menuTools.addAction(self.actionCategories)
        self.menuTools.addAction(self.actionProduct_And_Category_Relationship)
        self.menuTools.addAction(self.menuKeywords.menuAction())
        self.menuCharts.addAction(self.actionChartsBusinessReport)
        self.menubar.addAction(self.menuSystem.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuCharts.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.mainTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "NEWAIM Amazon Analysis"))
        self.mainTabs.setTabText(self.mainTabs.indexOf(self.tab), _translate("mainWindow", "Tab 1"))
        self.menuSystem.setTitle(_translate("mainWindow", "System"))
        self.menuHelp.setTitle(_translate("mainWindow", "Help"))
        self.menuTools.setTitle(_translate("mainWindow", "Amazon"))
        self.menuKeywords.setTitle(_translate("mainWindow", "Keywords"))
        self.menuCharts.setTitle(_translate("mainWindow", "Charts"))
        self.actionSetting.setText(_translate("mainWindow", "Configuration"))
        self.actionSetting.setShortcut(_translate("mainWindow", "Ctrl+Shift+S"))
        self.actionExit.setText(_translate("mainWindow", "Exit"))
        self.actionAbout.setText(_translate("mainWindow", "About"))
        self.actionAbout.setShortcut(_translate("mainWindow", "Ctrl+Shift+A"))
        self.actionBusinessReport.setText(_translate("mainWindow", "Business Report"))
        self.actionBusinessReport.setShortcut(_translate("mainWindow", "Ctrl+R"))
        self.actionProductList.setText(_translate("mainWindow", "Product List"))
        self.actionProductList.setShortcut(_translate("mainWindow", "Ctrl+P"))
        self.actionCategories.setText(_translate("mainWindow", "Category List"))
        self.actionCategories.setShortcut(_translate("mainWindow", "Ctrl+T"))
        self.actionDashboard.setText(_translate("mainWindow", "Dashboard"))
        self.actionDashboard.setShortcut(_translate("mainWindow", "Ctrl+D"))
        self.actionChartsBusinessReport.setText(_translate("mainWindow", "Business Report"))
        self.actionProduct_Line.setText(_translate("mainWindow", "Product Line"))
        self.actionProduct_Line.setShortcut(_translate("mainWindow", "Ctrl+G"))
        self.actionCategory_List.setText(_translate("mainWindow", "Category List"))
        self.actionCategory_List.setShortcut(_translate("mainWindow", "Ctrl+E"))
        self.actionKeywords_List.setText(_translate("mainWindow", "Keywords List"))
        self.actionKeywords_List.setShortcut(_translate("mainWindow", "Ctrl+N"))
        self.actionProduct_Category_Relation.setText(_translate("mainWindow", "Product Category Relation"))
        self.actionProduct_Category_Relation.setShortcut(_translate("mainWindow", "Ctrl+H"))
        self.actionProduct_And_Category_Relationship.setText(_translate("mainWindow", "Product Category Relation"))
        self.actionProduct_And_Category_Relationship.setShortcut(_translate("mainWindow", "Ctrl+B"))
        self.actionAmazon_Keyword_Relation.setText(_translate("mainWindow", "Amazon Product Relation"))
        self.actionAmazon_Keyword_Relation.setShortcut(_translate("mainWindow", "Ctrl+U"))
        self.actionAmazon_Category_Relation.setText(_translate("mainWindow", "Amazon Category Relation"))
        self.actionAmazon_Category_Relation.setShortcut(_translate("mainWindow", "Ctrl+M"))
        self.actionHelp.setText(_translate("mainWindow", "Help"))


import icons_rc
