# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetWeb.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_WebForm(object):
    def setupUi(self, WebForm):
        WebForm.setObjectName("WebForm")
        WebForm.resize(795, 604)
        WebForm.setStyleSheet("background-color: rgb(234, 234, 234);")
        self.vlWebForm = QtWidgets.QVBoxLayout(WebForm)
        self.vlWebForm.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.vlWebForm.setContentsMargins(0, 0, 0, 0)
        self.vlWebForm.setObjectName("vlWebForm")
        self.hlWebForm = QtWidgets.QHBoxLayout()
        self.hlWebForm.setObjectName("hlWebForm")
        self.widgetNav = QtWidgets.QWidget(WebForm)
        self.widgetNav.setMinimumSize(QtCore.QSize(100, 0))
        self.widgetNav.setStyleSheet("background-color: rgb(227, 227, 227);")
        self.widgetNav.setObjectName("widgetNav")
        self.formLayout = QtWidgets.QFormLayout(self.widgetNav)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.DontWrapRows)
        self.formLayout.setContentsMargins(3, 0, 3, 3)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(8)
        self.formLayout.setObjectName("formLayout")
        self.widget = QtWidgets.QWidget(self.widgetNav)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(20, 26))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 3, 0, 3)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.tbRedo = QtWidgets.QToolButton(self.widget)
        self.tbRedo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbRedo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button/images/button/redo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbRedo.setIcon(icon)
        self.tbRedo.setAutoRaise(True)
        self.tbRedo.setObjectName("tbRedo")
        self.gridLayout.addWidget(self.tbRedo, 0, 2, 1, 1)
        self.tbRefresh = QtWidgets.QToolButton(self.widget)
        self.tbRefresh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbRefresh.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button/images/button/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbRefresh.setIcon(icon1)
        self.tbRefresh.setAutoRaise(True)
        self.tbRefresh.setObjectName("tbRefresh")
        self.gridLayout.addWidget(self.tbRefresh, 0, 0, 1, 1)
        self.tbGoBack = QtWidgets.QToolButton(self.widget)
        self.tbGoBack.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbGoBack.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button/images/button/back.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbGoBack.setIcon(icon2)
        self.tbGoBack.setAutoRaise(True)
        self.tbGoBack.setObjectName("tbGoBack")
        self.gridLayout.addWidget(self.tbGoBack, 0, 1, 1, 1)
        self.tbStop = QtWidgets.QToolButton(self.widget)
        self.tbStop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbStop.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/button/images/button/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbStop.setIcon(icon3)
        self.tbStop.setAutoRaise(True)
        self.tbStop.setObjectName("tbStop")
        self.gridLayout.addWidget(self.tbStop, 0, 3, 1, 1)
        self.tbSide = QtWidgets.QToolButton(self.widget)
        self.tbSide.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbSide.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/button/images/button/left.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSide.setIcon(icon4)
        self.tbSide.setShortcut("")
        self.tbSide.setAutoRaise(True)
        self.tbSide.setObjectName("tbSide")
        self.gridLayout.addWidget(self.tbSide, 0, 4, 1, 1)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.widget)
        self.labelField = QtWidgets.QLabel(self.widgetNav)
        self.labelField.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.labelField.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelField.setObjectName("labelField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.labelField)
        self.leField = QtWidgets.QLineEdit(self.widgetNav)
        self.leField.setFrame(True)
        self.leField.setClearButtonEnabled(True)
        self.leField.setObjectName("leField")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.leField)
        self.tbGo = QtWidgets.QToolButton(self.widgetNav)
        self.tbGo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbGo.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/button/images/button/right.gif"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbGo.setIcon(icon5)
        self.tbGo.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.tbGo.setAutoRaise(True)
        self.tbGo.setObjectName("tbGo")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.tbGo)
        self.pbGo = QtWidgets.QPushButton(self.widgetNav)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbGo.sizePolicy().hasHeightForWidth())
        self.pbGo.setSizePolicy(sizePolicy)
        self.pbGo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/button/images/svg/angle-right-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbGo.setIcon(icon6)
        self.pbGo.setIconSize(QtCore.QSize(20, 20))
        self.pbGo.setAutoDefault(False)
        self.pbGo.setDefault(True)
        self.pbGo.setFlat(True)
        self.pbGo.setObjectName("pbGo")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.pbGo)
        self.hlWebForm.addWidget(self.widgetNav)
        self.widgetContent = QtWidgets.QWidget(WebForm)
        self.widgetContent.setMouseTracking(True)
        self.widgetContent.setTabletTracking(True)
        self.widgetContent.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.widgetContent.setAcceptDrops(True)
        self.widgetContent.setObjectName("widgetContent")
        self.widgetContentVL = QtWidgets.QVBoxLayout(self.widgetContent)
        self.widgetContentVL.setContentsMargins(0, 0, 0, 0)
        self.widgetContentVL.setObjectName("widgetContentVL")
        self.hlWebForm.addWidget(self.widgetContent)
        self.hlWebForm.setStretch(1, 10)
        self.vlWebForm.addLayout(self.hlWebForm)

        self.retranslateUi(WebForm)
        QtCore.QMetaObject.connectSlotsByName(WebForm)
        WebForm.setTabOrder(self.tbRefresh, self.tbGoBack)
        WebForm.setTabOrder(self.tbGoBack, self.tbRedo)
        WebForm.setTabOrder(self.tbRedo, self.tbStop)
        WebForm.setTabOrder(self.tbStop, self.tbSide)
        WebForm.setTabOrder(self.tbSide, self.leField)
        WebForm.setTabOrder(self.leField, self.tbGo)
        WebForm.setTabOrder(self.tbGo, self.pbGo)

    def retranslateUi(self, WebForm):
        _translate = QtCore.QCoreApplication.translate
        WebForm.setWindowTitle(_translate("WebForm", "Form"))
        self.tbRedo.setToolTip(_translate("WebForm", "Forward"))
        self.tbRefresh.setToolTip(_translate("WebForm", "Refresh"))
        self.tbGoBack.setToolTip(_translate("WebForm", "Go Back"))
        self.tbStop.setToolTip(_translate("WebForm", "Stop"))
        self.tbSide.setToolTip(_translate("WebForm", "Collapse"))
        self.labelField.setText(_translate("WebForm", "TextLabel"))
        self.tbGo.setToolTip(_translate("WebForm", "Go"))
        self.pbGo.setText(_translate("WebForm", "PushButton"))

import icons_rc
