# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widgetSearchField.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SearchFieldForm(object):
    def setupUi(self, SearchFieldForm):
        SearchFieldForm.setObjectName("SearchFieldForm")
        SearchFieldForm.resize(882, 188)
        SearchFieldForm.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SearchFieldForm)
        self.horizontalLayout.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(SearchFieldForm)
        self.widget.setMinimumSize(QtCore.QSize(220, 0))
        self.widget.setMaximumSize(QtCore.QSize(220, 16777215))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setContentsMargins(3, 3, 3, 3)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_3 = QtWidgets.QWidget(self.widget)
        self.widget_3.setMinimumSize(QtCore.QSize(150, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.leValue = QtWidgets.QLineEdit(self.widget_3)
        self.leValue.setMinimumSize(QtCore.QSize(150, 20))
        self.leValue.setMaximumSize(QtCore.QSize(150, 20))
        self.leValue.setDragEnabled(True)
        self.leValue.setObjectName("leValue")
        self.verticalLayout.addWidget(self.leValue)
        self.dteValue = QtWidgets.QDateTimeEdit(self.widget_3)
        self.dteValue.setMinimumSize(QtCore.QSize(150, 20))
        self.dteValue.setMaximumSize(QtCore.QSize(150, 20))
        self.dteValue.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dteValue.setMinimumDate(QtCore.QDate(2000, 1, 1))
        self.dteValue.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dteValue.setCalendarPopup(True)
        self.dteValue.setObjectName("dteValue")
        self.verticalLayout.addWidget(self.dteValue)
        self.floatValue = QtWidgets.QDoubleSpinBox(self.widget_3)
        self.floatValue.setMinimumSize(QtCore.QSize(150, 20))
        self.floatValue.setMaximumSize(QtCore.QSize(150, 20))
        self.floatValue.setDecimals(4)
        self.floatValue.setMaximum(9999999999.99)
        self.floatValue.setObjectName("floatValue")
        self.verticalLayout.addWidget(self.floatValue)
        self.intValue = QtWidgets.QSpinBox(self.widget_3)
        self.intValue.setMinimumSize(QtCore.QSize(150, 20))
        self.intValue.setMaximumSize(QtCore.QSize(150, 20))
        self.intValue.setMinimum(-999999999)
        self.intValue.setMaximum(999999999)
        self.intValue.setSingleStep(1)
        self.intValue.setObjectName("intValue")
        self.verticalLayout.addWidget(self.intValue)
        self.comboValue = QtWidgets.QComboBox(self.widget_3)
        self.comboValue.setObjectName("comboValue")
        self.verticalLayout.addWidget(self.comboValue)
        self.gridLayout.addWidget(self.widget_3, 2, 4, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 2, 1, 1)
        self.labOperator = QtWidgets.QLabel(self.widget)
        self.labOperator.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labOperator.setObjectName("labOperator")
        self.gridLayout.addWidget(self.labOperator, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(60, 0))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.cbField = QtWidgets.QComboBox(self.widget)
        self.cbField.setMinimumSize(QtCore.QSize(150, 0))
        self.cbField.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbField.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbField.setObjectName("cbField")
        self.gridLayout.addWidget(self.cbField, 0, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 2, 1, 1)
        self.cbUnion = QtWidgets.QComboBox(self.widget)
        self.cbUnion.setMinimumSize(QtCore.QSize(150, 0))
        self.cbUnion.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbUnion.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbUnion.setObjectName("cbUnion")
        self.cbUnion.addItem("")
        self.cbUnion.addItem("")
        self.gridLayout.addWidget(self.cbUnion, 4, 4, 1, 1)
        self.cbOperator = QtWidgets.QComboBox(self.widget)
        self.cbOperator.setMinimumSize(QtCore.QSize(150, 0))
        self.cbOperator.setMaximumSize(QtCore.QSize(150, 16777215))
        self.cbOperator.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cbOperator.setObjectName("cbOperator")
        self.cbOperator.addItem("")
        self.cbOperator.addItem("")
        self.cbOperator.addItem("")
        self.cbOperator.addItem("")
        self.cbOperator.addItem("")
        self.cbOperator.addItem("")
        self.gridLayout.addWidget(self.cbOperator, 1, 4, 1, 1)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(SearchFieldForm)
        self.widget_2.setMinimumSize(QtCore.QSize(30, 0))
        self.widget_2.setObjectName("widget_2")
        self.tbAdd = QtWidgets.QToolButton(self.widget_2)
        self.tbAdd.setGeometry(QtCore.QRect(1, 4, 22, 22))
        self.tbAdd.setMinimumSize(QtCore.QSize(22, 22))
        self.tbAdd.setMaximumSize(QtCore.QSize(22, 22))
        self.tbAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbAdd.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button/images/svg/plus-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbAdd.setIcon(icon)
        self.tbAdd.setAutoRaise(True)
        self.tbAdd.setObjectName("tbAdd")
        self.tbUpdate = QtWidgets.QToolButton(self.widget_2)
        self.tbUpdate.setGeometry(QtCore.QRect(1, 30, 22, 22))
        self.tbUpdate.setMinimumSize(QtCore.QSize(22, 22))
        self.tbUpdate.setMaximumSize(QtCore.QSize(22, 22))
        self.tbUpdate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbUpdate.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/button/images/svg/save-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbUpdate.setIcon(icon1)
        self.tbUpdate.setAutoRaise(True)
        self.tbUpdate.setObjectName("tbUpdate")
        self.tbSub = QtWidgets.QToolButton(self.widget_2)
        self.tbSub.setGeometry(QtCore.QRect(1, 56, 22, 22))
        self.tbSub.setMinimumSize(QtCore.QSize(22, 22))
        self.tbSub.setMaximumSize(QtCore.QSize(22, 22))
        self.tbSub.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbSub.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/button/images/svg/minus-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSub.setIcon(icon2)
        self.tbSub.setAutoRaise(True)
        self.tbSub.setObjectName("tbSub")
        self.tbSearch = QtWidgets.QToolButton(self.widget_2)
        self.tbSearch.setGeometry(QtCore.QRect(1, 80, 25, 25))
        self.tbSearch.setMinimumSize(QtCore.QSize(25, 25))
        self.tbSearch.setMaximumSize(QtCore.QSize(25, 25))
        self.tbSearch.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbSearch.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/button/images/svg/search-solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tbSearch.setIcon(icon3)
        self.tbSearch.setIconSize(QtCore.QSize(22, 22))
        self.tbSearch.setCheckable(False)
        self.tbSearch.setAutoRepeat(False)
        self.tbSearch.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.tbSearch.setAutoRaise(True)
        self.tbSearch.setObjectName("tbSearch")
        self.horizontalLayout.addWidget(self.widget_2)
        self.twOperators = QtWidgets.QTableWidget(SearchFieldForm)
        self.twOperators.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.twOperators.setDragEnabled(False)
        self.twOperators.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.twOperators.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.twOperators.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.twOperators.setShowGrid(True)
        self.twOperators.setGridStyle(QtCore.Qt.SolidLine)
        self.twOperators.setCornerButtonEnabled(False)
        self.twOperators.setObjectName("twOperators")
        self.twOperators.setColumnCount(6)
        self.twOperators.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.twOperators.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.twOperators.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.twOperators.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.twOperators.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.twOperators.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.twOperators.setHorizontalHeaderItem(5, item)
        self.twOperators.horizontalHeader().setHighlightSections(False)
        self.horizontalLayout.addWidget(self.twOperators)
        self.horizontalLayout.setStretch(2, 1)

        self.retranslateUi(SearchFieldForm)
        QtCore.QMetaObject.connectSlotsByName(SearchFieldForm)

    def retranslateUi(self, SearchFieldForm):
        _translate = QtCore.QCoreApplication.translate
        SearchFieldForm.setWindowTitle(_translate("SearchFieldForm", "Form"))
        self.dteValue.setDisplayFormat(_translate("SearchFieldForm", "yyyy-M-d H:mm:ss"))
        self.label_2.setText(_translate("SearchFieldForm", "Value: "))
        self.labOperator.setText(_translate("SearchFieldForm", "Operator: "))
        self.label.setText(_translate("SearchFieldForm", "Field: "))
        self.label_3.setText(_translate("SearchFieldForm", "Union: "))
        self.cbUnion.setItemText(0, _translate("SearchFieldForm", "AND"))
        self.cbUnion.setItemText(1, _translate("SearchFieldForm", "OR"))
        self.cbOperator.setItemText(0, _translate("SearchFieldForm", "contains"))
        self.cbOperator.setItemText(1, _translate("SearchFieldForm", "="))
        self.cbOperator.setItemText(2, _translate("SearchFieldForm", ">"))
        self.cbOperator.setItemText(3, _translate("SearchFieldForm", "<"))
        self.cbOperator.setItemText(4, _translate("SearchFieldForm", ">="))
        self.cbOperator.setItemText(5, _translate("SearchFieldForm", "<="))
        self.tbSearch.setShortcut(_translate("SearchFieldForm", "Return"))
        item = self.twOperators.horizontalHeaderItem(0)
        item.setText(_translate("SearchFieldForm", "FieldName"))
        item = self.twOperators.horizontalHeaderItem(1)
        item.setText(_translate("SearchFieldForm", "Field"))
        item = self.twOperators.horizontalHeaderItem(2)
        item.setText(_translate("SearchFieldForm", "Operatior"))
        item = self.twOperators.horizontalHeaderItem(3)
        item.setText(_translate("SearchFieldForm", "Value"))
        item = self.twOperators.horizontalHeaderItem(4)
        item.setText(_translate("SearchFieldForm", "Union"))
        item = self.twOperators.horizontalHeaderItem(5)
        item.setText(_translate("SearchFieldForm", "Type"))


import icons_rc
