# Generated by Django 2.1.5 on 2019-06-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cronjob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('creator_id', models.IntegerField(editable=False, null=True, verbose_name='Creator')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True, verbose_name='Status')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='Sort')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Title')),
                ('send_status', models.IntegerField(choices=[(1, 'Successful'), (2, 'Unsuccessful'), (3, 'Error')], default=2, editable=False, verbose_name='Send Status')),
                ('sending_type', models.CharField(blank=True, max_length=50, verbose_name='Sending Type')),
                ('content', models.TextField(max_length=10000, null=True, verbose_name='Content')),
                ('condition', models.CharField(blank=True, max_length=255, verbose_name='Condition')),
                ('group_name', models.CharField(blank=True, max_length=50, verbose_name='Group Name')),
                ('token', models.CharField(blank=True, max_length=100, verbose_name='Token')),
                ('message_type', models.CharField(blank=True, max_length=50, verbose_name='Message Type')),
            ],
            options={
                'verbose_name': 'Task Message',
                'verbose_name_plural': 'Task Message',
                'db_table': 'task_message',
            },
        ),
        migrations.CreateModel(
            name='TaskActionLogModel',
            fields=[
            ],
            options={
                'verbose_name': 'Task Action Log',
                'verbose_name_plural': 'Task Action Log',
                'proxy': True,
                'indexes': [],
            },
            bases=('cronjob.cronjobstatemodel',),
        ),
        migrations.CreateModel(
            name='TaskQueueListModel',
            fields=[
            ],
            options={
                'verbose_name': 'Task Queue List',
                'verbose_name_plural': 'Task Queue List',
                'proxy': True,
                'indexes': [],
            },
            bases=('cronjob.cronjobjobstoremodel',),
        ),
        migrations.CreateModel(
            name='TaskRunLogModel',
            fields=[
            ],
            options={
                'verbose_name': 'Task Run Log',
                'verbose_name_plural': 'Task Run Log',
                'proxy': True,
                'indexes': [],
            },
            bases=('cronjob.cronjoblogsmodel',),
        ),
    ]
