# Generated by Django 2.2.3 on 2019-07-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0002_cronjobmodel_task_type'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCaptureListModel',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Capture List',
                'verbose_name': 'Capture List',
                'managed': False,
                'proxy': True,
            },
            bases=('cronjob.cronjobmodel',),
        ),
    ]
