# Generated by Django 2.2.3 on 2019-07-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0003_auto_20190710_1124'),
        ('task', '0002_taskcapturelistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTransformationListModel',
            fields=[
            ],
            options={
                'verbose_name': 'Transformation List',
                'verbose_name_plural': 'Transformation List',
                'managed': False,
                'proxy': True,
            },
            bases=('cronjob.cronjobmodel',),
        ),
    ]
