# Generated by Django 2.2.3 on 2019-07-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cronjob', '0003_auto_20190710_1124'),
        ('task', '0003_tasktransformationlistmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAnalysisListModel',
            fields=[
            ],
            options={
                'verbose_name': 'Analysis List',
                'verbose_name_plural': 'Analysis List',
                'managed': False,
                'proxy': True,
            },
            bases=('cronjob.cronjobmodel',),
        ),
        migrations.CreateModel(
            name='TaskOtherListModel',
            fields=[
            ],
            options={
                'verbose_name': 'Other List',
                'verbose_name_plural': 'Other List',
                'managed': False,
                'proxy': True,
            },
            bases=('cronjob.cronjobmodel',),
        ),
        migrations.CreateModel(
            name='TaskReportListModel',
            fields=[
            ],
            options={
                'verbose_name': 'Report List',
                'verbose_name_plural': 'Report List',
                'managed': False,
                'proxy': True,
            },
            bases=('cronjob.cronjobmodel',),
        ),
        migrations.DeleteModel(
            name='TaskMessageModel',
        ),
        migrations.DeleteModel(
            name='TaskActionLogModel',
        ),
        migrations.DeleteModel(
            name='TaskQueueListModel',
        ),
        migrations.DeleteModel(
            name='TaskRunLogModel',
        ),
    ]
