# Generated by Django 2.1.5 on 2019-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatAmazonSkuPriceLogDayDv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100, verbose_name='Asin')),
                ('sku', models.CharField(max_length=100, verbose_name='Sku')),
                ('dy', models.DateField(null=True, verbose_name='Day')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'Price Log for days',
                'db_table': 'view_i_amazon_sku_price_log_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatAmazonSkuPriceLogMonthDv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100, verbose_name='Asin')),
                ('sku', models.CharField(max_length=100, verbose_name='Sku')),
                ('yr', models.IntegerField(null=True, verbose_name='Year')),
                ('mo', models.IntegerField(null=True, verbose_name='Month')),
                ('first_day', models.DateField(null=True, verbose_name='First Day')),
                ('last_day', models.DateField(null=True, verbose_name='Last Day')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'Price Log for months',
                'db_table': 'view_i_amazon_sku_price_log_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatAmazonSkuPriceLogWeekDv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100, verbose_name='Asin')),
                ('sku', models.CharField(max_length=100, verbose_name='Sku')),
                ('yr', models.IntegerField(null=True, verbose_name='Year')),
                ('wk', models.IntegerField(null=True, verbose_name='Week')),
                ('first_day', models.DateField(null=True, verbose_name='First Day')),
                ('last_day', models.DateField(null=True, verbose_name='Last Day')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name_plural': 'Price Log for weeks',
                'db_table': 'view_i_amazon_sku_price_log_week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatAmazonSkuReviewRankDayDv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100, verbose_name='Asin')),
                ('sku', models.CharField(max_length=100, verbose_name='Sku')),
                ('dy', models.DateField(null=True, verbose_name='Day')),
                ('num', models.IntegerField(null=True, verbose_name='Count')),
            ],
            options={
                'verbose_name_plural': 'Review Rank for days',
                'db_table': 'view_i_amazon_sku_review_rank_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatAmazonSkuReviewRankMonthDv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100, verbose_name='Asin')),
                ('sku', models.CharField(max_length=100, verbose_name='Sku')),
                ('yr', models.IntegerField(null=True, verbose_name='Year')),
                ('mo', models.IntegerField(null=True, verbose_name='Month')),
                ('first_day', models.DateField(null=True, verbose_name='First Day')),
                ('last_day', models.DateField(null=True, verbose_name='Last Day')),
                ('num', models.IntegerField(null=True, verbose_name='Count')),
            ],
            options={
                'verbose_name_plural': 'Review Rank for months',
                'db_table': 'view_i_amazon_sku_review_rank_month',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatAmazonSkuReviewRankWeekDv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asin', models.CharField(max_length=100, verbose_name='Asin')),
                ('sku', models.CharField(max_length=100, verbose_name='Sku')),
                ('yr', models.IntegerField(null=True, verbose_name='Year')),
                ('wk', models.IntegerField(null=True, verbose_name='Week')),
                ('first_day', models.DateField(null=True, verbose_name='First Day')),
                ('last_day', models.DateField(null=True, verbose_name='Last Day')),
                ('num', models.IntegerField(null=True, verbose_name='Count')),
            ],
            options={
                'verbose_name_plural': 'Review Rank for weeks',
                'db_table': 'view_i_amazon_sku_review_rank_week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CaptureSkuPriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('creator_id', models.IntegerField(editable=False, null=True, verbose_name='Creator')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True, verbose_name='Status')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='Sort')),
                ('platform', models.CharField(default='amazon', max_length=100, verbose_name='Platform')),
                ('platform_id', models.IntegerField(default=0, editable=False, null=True, verbose_name='Platform Id')),
                ('sku', models.CharField(max_length=100, verbose_name='Sku')),
                ('asin', models.CharField(max_length=100, verbose_name='Asin')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price')),
                ('link', models.CharField(max_length=255, verbose_name='Link')),
                ('capture_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Capture At')),
            ],
            options={
                'verbose_name': 'Sku Price Log',
                'verbose_name_plural': 'Sku Price Log',
                'db_table': 'amazon_capture_sku_price',
            },
        ),
    ]
