# Generated by Django 2.2 on 2019-07-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_captureskupricemodel_statamazonskupricelogdaydv_statamazonskupricelogmonthdv_statamazonskupricelogwe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Category Code'),
        ),
    ]
