# Generated by Django 2.2.3 on 2019-07-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_auto_20190711_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Category Code'),
        ),
    ]
