# Generated by Django 2.2 on 2019-07-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0003_auto_20190711_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAsinLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('creator_id', models.IntegerField(editable=False, null=True, verbose_name='Creator')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True, verbose_name='Status')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='Sort')),
                ('sku', models.CharField(max_length=100, null=True, verbose_name='Product SKU')),
                ('modify_fields', models.CharField(max_length=200, null=True, verbose_name='Modify Field')),
                ('old_val', models.TextField(null=True, verbose_name='Old Value')),
                ('new_val', models.TextField(null=True, verbose_name='New Value')),
            ],
            options={
                'verbose_name': 'Product Modify Log',
                'verbose_name_plural': 'Product Modify Logs',
                'db_table': 'na_product_mod_log',
            },
        ),
        migrations.CreateModel(
            name='ProductCategoryLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Update At')),
                ('creator_id', models.IntegerField(editable=False, null=True, verbose_name='Creator')),
                ('status', models.IntegerField(choices=[(1, 'Enabled'), (2, 'Disabled')], default=1, null=True, verbose_name='Status')),
                ('sort', models.IntegerField(default=0, null=True, verbose_name='Sort')),
                ('category', models.CharField(max_length=100, null=True, verbose_name='Product Category')),
                ('modify_fields', models.CharField(max_length=200, null=True, verbose_name='Modify Field')),
                ('old_val', models.TextField(null=True, verbose_name='Old Value')),
                ('new_val', models.TextField(null=True, verbose_name='New Value')),
            ],
            options={
                'verbose_name': 'Product Category Modify Log',
                'verbose_name_plural': 'Product Category  Modify Logs',
                'db_table': 'pub_product_category_mod_log',
            },
        ),
    ]
