# Generated by Django 2.2 on 2019-07-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_auto_20190711_1636'),
        ('amazon', '0004_productasinlogmodel_productcategorylogmodel'),
    ]

    operations = [
    ]
