# Generated by Django 2.2.3 on 2019-07-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0006_auto_20190716_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategorymodel',
            name='code',
        ),
        migrations.RemoveField(
            model_name='productcategorymodel',
            name='parent',
        ),
    ]
