# Generated by Django 2.2 on 2019-07-23 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appfront', '0011_auto_20190722_1853'),
        ('amazon', '0008_auto_20190716_1628'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategoryLogModel',
            new_name='AmazonProductCategoryLogModel',
        ),
        migrations.RenameModel(
            old_name='ProductCategoryModel',
            new_name='AmazonProductCategoryModel',
        ),
    ]
