# Generated by Django 2.2.3 on 2019-08-02 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0012_auto_20190731_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='captureskureviewmodel',
            name='review_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Review Id'),
        ),
        migrations.AlterField(
            model_name='amazonproductcategorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.AmazonProductCategoryModel'),
        ),
    ]
