# Generated by Django 2.2 on 2019-08-05 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_auto_20190802_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmazonProductCategoryKeywordRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.AmazonProductCategoryModel', verbose_name='Amazon Category')),
                ('amazon_keyword_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.SkuKeywordModel', verbose_name='Amazon Keyword')),
            ],
            options={
                'db_table': 'amazon_product_category_keyword_relation',
            },
        ),
        migrations.AddField(
            model_name='amazonproductcategorymodel',
            name='keyword',
            field=models.ManyToManyField(through='amazon.AmazonProductCategoryKeywordRelation', to='amazon.SkuKeywordModel', verbose_name='Keyword'),
        ),
    ]
