# Generated by Django 2.2 on 2019-08-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0015_auto_20190805_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproductcategorymodel',
            name='url_alias',
            field=models.CharField(max_length=200, null=True, verbose_name='Url Alias'),
        ),
    ]
