# Generated by Django 2.2 on 2019-08-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentmodel',
            name='purchase_id',
            field=models.CharField(max_length=200, null=True, verbose_name='Purchase Department Id'),
        ),
    ]
