from task.forms.TaskCaptureForm import *
from task.forms.TaskTransformationForm import *
from task.forms.TaskAnalysisForm import *
from task.forms.TaskMessageForm import *
from task.forms.TaskReportForm import *
from task.forms.TaskOtherForm import *
from task.forms.TaskCaptureLogsForm import *
from task.forms.TaskTransformationLogsForm import *
from task.forms.TaskAnalysisLogsForm import *
from task.forms.TaskMessageLogsForm import *
from task.forms.TaskReportLogsForm import *
from task.forms.TaskOtherLogsForm import *